### ISSUE TITLE
[0.1.0-canary.x] FOUC + Flash of "Unthemed" Content in Next.js SSR

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#404]
# Bug report

## Describe the bug

I've managed to pretty much fully migrate my personal Next.js site over to Stitches beta:

- Current state: [joebell.co.uk](https://joebell.co.uk)
- Stitches version: https://joebell-git-refactor-stitches.joebell.now.sh/

I'm super happy with the new Custom Property-powered DX (thank you for your hard work on this), but unfortunately I'm suffering from what I expect to be SSR-related issues; **on initial load/hard refresh, FOUC or Flash of "unthemed" Content occurs**.

This is particularly noticeable on Firefox when visiting the blog post pages at https://joebell-git-refactor-stitches.joebell.now.sh/.

## To Reproduce

My personal site is a private project, but I've managed to build a minimal reproduction:

* **Minimal Repro Source Code:** https://github.com/joe-bell/issue-repro-stitches-ssr
* **Demo:** https://issue-repro-stitches-ssr.vercel.app/

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://issue-repro-stitches-ssr.vercel.app/ (or run locally `npm run build && npm run start`)
2. Note how the page loads without the theme, sometimes without styles altogether.
3. If this behaviour isn't visible, trigger a hard refresh in your browser (this is particularly noticeable in Firefox)

> Note: this behaviour isn't visible in Next.js development mode, only on `build`

## Expected behavior

- Pages should load without FOUC
- Pages should load with the initial theme (which in this case should be `$system` font–defined in `globalStyles`)

## Screenshots

https://user-images.githubusercontent.com/7349341/108180790-d7913d00-710f-11eb-9bf1-bd83a86587bc.mp4

## System information

- OS: macOS
- Browser (if applies): Edge, Firefox
- Version of Stitches: 0.1.0-canary.6
- Version of Node.js: 14.15.1

## Additional context

N/A

**Comment by jorenrui** [comment]
Ah I had the same problem before on my side project. I manage to fix it by doing this. Tho not really sure if this is the proper usage of `getCssString`. 😅

```diff
import React from 'react';
import NextDocument, {
  Head, Html, Main, NextScript,
} from 'next/document';

+ import { getCssString } from '@/lib/stitches';

class Document extends NextDocument {
  render() {
+    const styles = getCssString();

    return (
      <Html lang="en">
        <Head>
          {/* eslint-disable-next-line react/no-danger */}
+          <style dangerouslySetInnerHTML={{ __html: styles }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default Document;
```

I tried what you've tried here: https://sutle-ngv9peeb5.vercel.app/
I got some flash of unstyled content.

Then I've updated it to like the code above: https://sutle.io/
Now it works?

**Comment by joe-bell** [comment]
Thanks @jorenrui! I'll give this a try

**Comment by eddyw** [comment]
To add to @jorenrui reply, don't forget the `id`:
```javascript
<style id="stitches" dangerouslySetInnerHTML={{ __html: getCssString() }} />
```
It's used internally to lookup for an existing stitches stylesheet.

The reason why this doesn't work:
```javascript
<style id="stitches">{getCssString()}</style>
```
It's because React will escape certain characters such as single and double quotes, so you'd end up with broken styles, e.g:
```css
.some-classname {
  --fonts-body: &quot;Segoe UI&quot;
}
```

**Comment by joe-bell** [comment]
Looks like that worked a treat for resolving the Flash of "Unthemed" content, thank you @jorenrui 🎉 

Source: https://github.com/joe-bell/issue-repro-stitches-ssr/pull/2
Demo: https://issue-repro-stitches-ssr-git-fix-getcssstring.joebell.vercel.app/

Still getting a slight FOUC issue unfortunately, so I'll leave this issue open

**Comment by jonathantneal** [comment]
There was a separate issue with the SSR styles not matching the overwritten styles that might have further slowed browser resolution, resolved in #406.

Going even further, I’m considering a change that would delay rewriting the style tag by one frame if the style tag is populated with CSS. I’m not yet sure of this change, tho, because it would actually _create_ a problem for people with a purposefully incomplete `<style />` tag and who want things to **change** as fast as possible.

**Comment by jose-donato** [comment]
> To add to @jorenrui reply, don't forget the `id`:
> 
> ```js
> <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssString() }} />
> ```
> 
> It's used internally to lookup for an existing stitches stylesheet.
> 
> The reason why this doesn't work:
> 
> ```js
> <style id="stitches">{getCssString()}</style>
> ```
> 
> It's because React will escape certain characters such as single and double quotes, so you'd end up with broken styles, e.g:
> 
> ```css
> .some-classname {
>   --fonts-body: &quot;Segoe UI&quot;
> }
> ```

my styles are always overwritten if I set id="stitches". 

![image](https://user-images.githubusercontent.com/43375532/108615470-6518a980-73fc-11eb-8d35-86ed086fd6ee.png)

if i don't set I get two style tags, one empty.

here is my _document.tsx

```
import React from 'react';
import NextDocument, {
  Head, Html, Main, NextScript,
} from 'next/document';
import { getCssString } from 'stitches.config';
class Document extends NextDocument {
  render() {
    return (
      <Html lang="en">
        <Head>
          <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssString() }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
export default Document;
```

using "0.1.0-canary.12"

**Comment by joe-bell** [comment]
Hey @jonathantneal 👋 

I bumped https://joebell-git-refactor-stitches-joebell.vercel.app to **`0.1.0-canary.12`** and whatever changes you made recently have made a **massive** difference to the homepage performance

Some FOUC still occurs (albeit minor) on the `/blog` index and post pages, but just wanted to drop by to give an update + say thanks for your continued hard work on this!

I've bumped the example reproduction (same repo) to the latest canary too, hope it helps:
* original srr approach: issue-repro-stitches-ssr-n59serktx-joebell.vercel.app
* with [joeylene's approach](https://github.com/modulz/stitches/issues/404#issuecomment-780425562): issue-repro-stitches-ssr-nqmat0mca-joebell.vercel.app

**Comment by joe-bell** [comment]
# Temporary Workaround 👷🏼‍♂️

I've been messing around with some workaround strategies in the meantime and this seems to work well:

1. Hide the `body` by default (**unless JS is disabled**)
2. When Stitches styles are "ready", override the "hide" styles

> ⚠️ **This is just a workaround**

## Setup

1. Create a custom `_document.tsx`
    ```tsx diff
    // pages/_document.tsx
    import * as React from "react";
    import NextDocument, { Html, Head, Main, NextScript } from "next/document";
    import { getCssString } from "../stitches.config";
    
    export default class Document extends NextDocument {
      static async getInitialProps(ctx) {
        try {
          const initialProps = await NextDocument.getInitialProps(ctx);
    
          return {
            ...initialProps,
            styles: (
              <>
                {initialProps.styles}
                {/* Hide the body, unless JS is disabled */}
                <style
                  dangerouslySetInnerHTML={{
                    __html: "body { opacity: 0; visibility: hidden; }",
                  }}
                />
                <noscript>
                  <style
                    dangerouslySetInnerHTML={{
                      __html: "body { opacity: 1; visibility: visible; }",
                    }}
                  />
                </noscript>
                {/* Stitches CSS */}
                <style
                  id="stitches"
                  dangerouslySetInnerHTML={{ __html: getCssString() }}
                />
              </>
            ),
          };
        } finally {
        }
      }
    
      render() {
        return (
          <Html lang="en">
            <Head />
            <body>
              <Main />
              <NextScript />
            </body>
          </Html>
        );
      }
    }
    ```
2. In your `stitches.config.ts` add some `global` css to override the "hide" style
    ```ts
    // stitches.config.ts
    export const globalStyles = global({
      body: {
        opacity: 1,
        visibility: "visible",
      },
    });
    ```
3. Create a custom `_app.tsx` file and call the `globalStyles()`
    ```ts
    // pages/_app.tsx
    import * as React from "react";
    import { AppProps } from "next/app";
    import { globalStyles } from "../stitches.config";
    
    const App = ({ Component, pageProps }: AppProps) => {
      globalStyles();
      return (
        <Component {...pageProps} />
      );
    };
    
    export default App;
    ```
4. ??Profit

**Comment by peduarte** [comment]
Fixed in 0.1.1 https://github.com/modulz/stitches/releases/tag/v0.1.1
