### ISSUE TITLE
[0.2.x] Creating `theme` is ~30-40x slower than alpha

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#656]
# Bug report

## Describe the bug

Hey

So we have something like [this](https://codesandbox.io/s/admiring-firefly-vrtf0?file=/src/App.tsx) implemented in our moderately large sized React app which is running on alpha version of stitches.

Earlier we tried migrating to the beta `0.1.x` versions and quickly ran into perf issues.

It seems most of the issues have been solved since except for this one.

## To Reproduce

Visit the below codesandbox and check console:

alpha: https://codesandbox.io/s/agitated-boyd-sxmql?file=/src/stitches.config.ts
![Screenshot 2021-06-07 at 10 03 09 PM](https://user-images.githubusercontent.com/14029371/121056813-39b7a000-c7dc-11eb-9a30-2c3ba0061894.png)

beta (canary): https://codesandbox.io/s/vigorous-rubin-08xmr?file=/src/stitches.config.ts
![Screenshot 2021-06-07 at 10 03 33 PM](https://user-images.githubusercontent.com/14029371/121056868-489e5280-c7dc-11eb-872c-1a8a8977a614.png)

## Expected behavior

_`theme` should go brrrr_

## Additional context

In continuation to https://github.com/modulz/stitches/issues/535#issuecomment-860943486

**Comment by jonathantneal** [comment]
Ah! This was resolved in the v0.2.x version and remains resolved in v1. I see https://github.com/modulz/stitches/issues/535 was closed, so I’m going to close this one as well. Of course, please raise an issue if you see any regressions.

**Comment by afzalsayed96** [comment]
Hey @jonathantneal,

As noted in https://github.com/modulz/stitches/issues/535#issuecomment-856087834 and https://github.com/modulz/stitches/issues/535#issuecomment-860943486, this was in fact  not resolved. This issue was created on @peduarte's suggestion in the above mentioned comment on #535.

I know a lot of perf issues were resolved in #535 but I would love to know your thoughts on the possibility of any further improvements in the `theme` function. And whether it would be possible to get it anywhere to `v0.1.x` speed.

**Comment by StephenHaney** [comment]
Hey 👋  — I'll pick up this thread since I have this situation loaded in memory.

Yes, the theme function did become slower in the beta due to picking up more functionality.

However, as far as I can tell, it's still very fast in real world applications, to the point it should never be the bottleneck.

Jonathan did add some caching after you provided the initial benchmark, so now the 1000 benchmark completes about  in 10ms on my machine (M1 Mac Mini).

Looking at your color picker use case, a single `theme` call, like in your use case, completes in 1/10th of a millisecond, which should be ok for your frame budget? If you're not already, can also consider throttling or raf'ing the change handler so it only runs every 16ms.

Please let me know if you aren't seeing the same thing and apologies for not communicating our take on this particular issue better.
